config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  resources :match_profiles
  resources :profiles
  resources :users, except: [:new]

  # TODO: create a pages model?
  # get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/match_profile.rb
class MatchProfile < ApplicationRecord
end

app/controllers/match_profiles_controller.rb
class MatchProfilesController < ApplicationController
  before_action :set_match_profile, only: %i[ show edit update destroy ]

  # GET /match_profiles or /match_profiles.json
  def index
    @match_profiles = MatchProfile.all
  end

  # GET /match_profiles/1 or /match_profiles/1.json
  def show
  end

  # GET /match_profiles/new
  def new
    @match_profile = MatchProfile.new
  end

  # GET /match_profiles/1/edit
  def edit
  end

  # POST /match_profiles or /match_profiles.json
  def create
    @match_profile = MatchProfile.new(match_profile_params)

    respond_to do |format|
      if @match_profile.save
        format.html { redirect_to match_profile_url(@match_profile), notice: "Match profile was successfully created." }
        format.json { render :show, status: :created, location: @match_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /match_profiles/1 or /match_profiles/1.json
  def update
    respond_to do |format|
      if @match_profile.update(match_profile_params)
        format.html { redirect_to match_profile_url(@match_profile), notice: "Match profile was successfully updated." }
        format.json { render :show, status: :ok, location: @match_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_profiles/1 or /match_profiles/1.json
  def destroy
    @match_profile.destroy

    respond_to do |format|
      format.html { redirect_to match_profiles_url, notice: "Match profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_profile
      @match_profile = MatchProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_profile_params
      params.fetch(:match_profile, {})
    end
end

app/helpers/match_profiles_helper.rb
module MatchProfilesHelper
end

app/views/match_profiles/_form.html.erb
<%= form_with(model: match_profile) do |form| %>
  <% if match_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match_profile.errors.count, "error") %> prohibited this match_profile from being saved:</h2>

      <ul>
        <% match_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/match_profiles/_match_profile.html.erb
<div id="<%= dom_id match_profile %>">
</div>

app/views/match_profiles/edit.html.erb
<h1>Editing match profile</h1>

<%= render "form", match_profile: @match_profile %>

<br>

<div>
  <%= link_to "Show this match profile", @match_profile %> |
  <%= link_to "Back to match profiles", match_profiles_path %>
</div>

app/views/match_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Match profiles</h1>

<div id="match_profiles">
  <% @match_profiles.each do |match_profile| %>
    <%= render match_profile %>
    <p>
      <%= link_to "Show this match profile", match_profile %>
    </p>
  <% end %>
</div>

<%= link_to "New match profile", new_match_profile_path %>

app/views/match_profiles/new.html.erb
<h1>New match profile</h1>

<%= render "form", match_profile: @match_profile %>

<br>

<div>
  <%= link_to "Back to match profiles", match_profiles_path %>
</div>

app/views/match_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match_profile %>

<div>
  <%= link_to "Edit this match profile", edit_match_profile_path(@match_profile) %> |
  <%= link_to "Back to match profiles", match_profiles_path %>

  <%= button_to "Destroy this match profile", @match_profile, method: :delete %>
</div>